package app.models;

import lombok.Builder;
import lombok.Data;

@Data
@Builder
public class Box {

    String receiver;
    double weight;
    String color;
    String destinationCountry;
    double shippingCost;

    //This overwrites Lamboks non-public autogenerated builder.
    public static class BoxBuilder{
        public BoxBuilder(){
        }
    }

}
